name: sport_depot
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

# PACKAGES

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  get: ^4.6.6
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.5
  get_storage: ^2.1.1
  firebase_core: ^2.27.2
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # LOCAL ASSETS

  assets:
    # - assets/icons
    # - assets/images/brands
    # - assets/logos
    # - assets/images
    # Logos
    - assets/logos/sd-store-splash-logo-black.png
    - assets/logos/sd-store-splash-logo-white.png
    - assets/logos/facebook-logo.png
    - assets/logos/google-logo.png
    # Onboarding images
    - assets/images/on_boarding_images/taxi-delivery-scooter-with-boxes.gif
    - assets/images/on_boarding_images/taxi-penguins-riding-on-an-ice-floe.gif
    - assets/images/on_boarding_images/taxi-rocket-delivering-parcels-to-aliens-in-space.gif
    # Animations
    - assets/images/animations/taxi-data-science-graphs-on-pc-screen.gif
    - assets/images/animations/taxi-cow-being-abducted-by-ufo.gif
    - assets/images/animations/taxi-people-waving-flags-at-ufos.gif
    - assets/images/animations/taxi-4.gif
    - assets/images/animations/taxi-teamwork-in-office.gif
    - assets/images/animations/taxi-woman-joining-puzzle-pieces-together.gif
    # Categories
    - assets/icons/categories/casual-t-shirt-.png
    - assets/icons/categories/sport-shoe.png
    # Banners
    - assets/images/banners/nike-banner1.png
    - assets/images/banners/under-armour-banner.png
    - assets/images/banners/garmin-banner.jpg
    # Products
    - assets/images/products/
    # User
    - assets/images/user/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica_regular.otf
        - asset: assets/fonts/coolvetica_regular_italic.otf
          style: italic
