// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxRQExUam9QybYzVGgFB60Dj13uSwzLkE',
    appId: '1:691428856787:web:39a46a333353c8836d1526',
    messagingSenderId: '691428856787',
    projectId: 'sportdepotstore',
    authDomain: 'sportdepotstore.firebaseapp.com',
    storageBucket: 'sportdepotstore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPebsH9T9qjVIIMTbdGys_qycxfAI4Q4g',
    appId: '1:691428856787:android:18eea6c7bf7a23fe6d1526',
    messagingSenderId: '691428856787',
    projectId: 'sportdepotstore',
    storageBucket: 'sportdepotstore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0Ys6Bxccjr2fDena0rs5sEEbaaCMza4',
    appId: '1:691428856787:ios:c0adc417cb99e8b76d1526',
    messagingSenderId: '691428856787',
    projectId: 'sportdepotstore',
    storageBucket: 'sportdepotstore.appspot.com',
    androidClientId: '691428856787-s5gpdhssejo2hrjl41m9d8tmug4ivave.apps.googleusercontent.com',
    iosClientId: '691428856787-avberlugch5fcil15npueq6cophal6jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportDepot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjyjRJ8uLj7ylY902FIoLlBuM0rMw5WS4',
    appId: '1:175073769890:ios:1767321c75b19c2b9e9afb',
    messagingSenderId: '175073769890',
    projectId: 'sport-depot-app',
    storageBucket: 'sport-depot-app.appspot.com',
    iosBundleId: 'com.example.sportDepot.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxRQExUam9QybYzVGgFB60Dj13uSwzLkE',
    appId: '1:691428856787:web:a6b3cc1a4292942e6d1526',
    messagingSenderId: '691428856787',
    projectId: 'sportdepotstore',
    authDomain: 'sportdepotstore.firebaseapp.com',
    storageBucket: 'sportdepotstore.appspot.com',
  );

}