// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSIYvDqQ69v0sgZombaDuKnI7_DBCM49c',
    appId: '1:175073769890:web:052a115d7e4518839e9afb',
    messagingSenderId: '175073769890',
    projectId: 'sport-depot-app',
    authDomain: 'sport-depot-app.firebaseapp.com',
    storageBucket: 'sport-depot-app.appspot.com',
    measurementId: 'G-7Q9FVYY6XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWdn2c8A4vDWNTV_n6aR21jl_HJBHxIlw',
    appId: '1:175073769890:android:bf7d2c95e85917919e9afb',
    messagingSenderId: '175073769890',
    projectId: 'sport-depot-app',
    storageBucket: 'sport-depot-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjyjRJ8uLj7ylY902FIoLlBuM0rMw5WS4',
    appId: '1:175073769890:ios:a1475e005c9fe3649e9afb',
    messagingSenderId: '175073769890',
    projectId: 'sport-depot-app',
    storageBucket: 'sport-depot-app.appspot.com',
    iosBundleId: 'com.example.sportDepot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjyjRJ8uLj7ylY902FIoLlBuM0rMw5WS4',
    appId: '1:175073769890:ios:1767321c75b19c2b9e9afb',
    messagingSenderId: '175073769890',
    projectId: 'sport-depot-app',
    storageBucket: 'sport-depot-app.appspot.com',
    iosBundleId: 'com.example.sportDepot.RunnerTests',
  );
}
